### ISSUE TITLE
Multitenancy leak HTTP headers between completely unrelated requests

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-multitenancy#143]
### Expected Behavior

This is a strange one. HTTP headers leak between requests. Its complicated to explain but I have a reproducer application.
In our setup we have three services, A, B and C.
The service (A) main purpose is to listen for Kafka events, make a HTTP GET request to service B, process data, then POST result to service C.
Getting data from service B is done with a declarative HTTP client and the client method contains Header annotations for tenant and bearer token.
```
Mono<Data> getData(@Header("X-Tenant") @NotNull String tenant, @Header @NotNull String authorization, @NotNull String id);
```
Posting result to service C is done with another declarative HTTP client and the client method contains same Header annotations.

```
Mono<List<Result>> uploadResult(@Header("X-Tenant") @NotNull String tenant, @Header @NotNull String authorization, @NotNull String id, @Body MultipartBody body);
```
Micronaut multitenancy dependency is installed because other parts of the service uses tenant propagation. It reads/writes the X-Tenant header. But the code path in this test case does not use automatic tenant propagation. It sets the X-Tenant header programatically in the client request.
Micrometer Prometheus dependency is installed and the /prometheus endpoint is scraped regularly.
We noticed in the logs a number of uploadResult requests got unauthorized errors. To my surprise I found that sometimes the value bound to the X-Tenant header when posting result to service C was the tenant that **only prometheus uses**!.
If I disable this endpoint in prometheus. The problem never appear. But in theory, if this is Micronaut or Netty leaking header values, then we should see this problem with other tenants. But I only see the Prometheus tenant in the error logs.

I expect http client calls initiated from a scheduled task or messages listener to not suffer interference from other inbound requests.

### Actual Behaviour

Sometimes when doing a client request and passing a header value, the actual X-Tenant contains a value from another request. The prometheus request!

### Steps To Reproduce

See reproducer application developed with Micronaut 3.7.2
./gradlew run
In another window run:
while true; do sleep 1; curl -H "X-Tenant: foo" http://localhost:8080/prometheus; done
After a few "Success" messages you will hopefully see "Unexpected header value: foo"

### Environment Information

MacOS 12.6
JDK 17

### Example Application

https://github.com/goeh/micronaut-header-leak-issue

### Version

3.7.2

**Comment by goeh** [comment]
Setting `micronaut.multitenancy.propagation.enabled` to `false` make the problem go away. But unfortunately that's currently not an option for us.

**Comment by goeh** [comment]
I am worried that this is not just a multitenancy issue, but something more generic http client or filter problem. I hope I'm wrong. Cc @sdelamo in case this repo is not actively monitored.

**Comment by sdelamo** [comment]
@timyates can you check this out?

**Comment by yawkat** [comment]
i talked some more with tim about this. a second problem is getting the *server* request inside a *client* filter on a client being called in a controller. using the thread local for this is a bit dodgy. however there are some tests in micronaut-core that make very sure that the request makes it through the reactive context, so it should be safe to use the server request registered in the reactive context.

**Comment by goeh** [comment]
I upgraded the sample application to Micronaut 3.7.5. Issue remains. But that was expected.

**Comment by yawkat** [comment]
@goeh sorry, we forgot about this issue.

There *is* a bug in the filter request propagation, but fixing it would not fix your test case. The problem in your test case is that you are configuring client request propagation, but also using the client in places where there is no context to propagate (in the `@Scheduled`, and *particularly* in the `.flatMap` there, which runs in the client event loop). 

Now the curl requests, which are processed on the server event loop (same as client event loop by default), they set the context and it's not always cleaned up. This causes the request context for the curl requests to sometimes leak into the context-less client requests in your scheduler.

There's two issues here:

1. the context from the curl request shouldn't remain set. This needs to be fixed in core, but it will be hard to avoid breaking anything. Probably 4.0.
2. the request context is loaded in the initial client.exchange call, and then made available to the client filters via the thread-local ServerRequestContext. However this is only set once, for the first filter. In your test project, the first filter does metrics, and it's reactive, so the thread-local doesn't always propagate to downstream filters. This is also a bug in core and needs to be fixed as part of https://github.com/micronaut-projects/micronaut-core/pull/8422. It could also be fixed in micronaut-multitenancy by using the reactive context instead of the thread-local context, but imo a core fix is sufficient.

However even if (2) was fixed, your issue would still appear. This is because of the client call in the flatMap, which runs on the client event loop. So the initial client.exchange of that client call sees the context leaked because of (1), and then correctly propagates it to all the filters. 

Now for you I see two immediate solutions. One is to work around (1) by using a separate event loop for the client and the server. This works well for your test case, however it is a bit fragile as a solution, because a leak could also happen on the client event loop depending on use elsewhere.

The best immediate solution would be to configure propagation so that it does not apply to clients that do not need it. E.g. you could have a separate service id for the client you use in the scheduler. If you can make this solution work, it is the least brittle.

**Comment by goeh** [comment]
Thank you for the deep info and research, much appreciated. I will try the "separate service id" proposal. I think it will work. Thanks.

**Comment by goeh** [comment]
FYI: I tried to disable tenant propagation with
```
micronaut:
  multitenancy:
    propagation:
      enabled: false
```
but that did not fix the issue. However, disabling tenant header writer "fixed" the issue.
```
micronaut:
    tenantwriter:
      httpheader:
        enabled: false
```
We already started to deprecate the use of automatic tenant propagation in our codebase some time ago, because of problems with reactive code. I think we will continue / finish that work and control the passing of correct tenant through services ourself. That ways it's clearer how is works, no magic behind the scenes.
